config/routes.rb
Rails.application.routes.draw do
  root "organizations#index"

  resource :first_run, only: %i[show create], path: "setup"

  resources :users do
    scope module: "users" do
      resource :profile
    end
  end

  resource :session
  resources :passwords, param: :token

  get "organization/:uid/join/:join_code", to: "users#new", as: :join
  post "organization/:uid/join/:join_code", to: "users#create"

  resources :organizations, param: :uid, except: %i[ index show ] do
    scope module: "organizations" do
      resource :join_code, only: :create
    end
    resources :patient_records
    resources :services
  end

  get "/:slug", to: "organizations#show", as: :slugged_organization

  get "organization/:uid/administratorships", to: "administratorships#index",  constraints: { uid: /\d+/ }, as: :slugged_organization_administratorships
  get "organization/:uid/administratorships/:id", to: "administratorships#index",  constraints: { uid: /\d+/ }, as: :slugged_organization_administratorship
  patch "organization/:uid/administratorships/:id", to: "administratorships#update", constraints: { uid: /\d+/ }

  get "up", to: "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker", to: "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest", to: "rails/pwa#manifest", as: :pwa_manifest
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :organization

  # has_one_attached :cover, dependent: :purge_later
  normalizes :name, with: ->(name) { name.downcase }
  validates :name, presence: true, uniqueness: { scope: :organization }
  validates :cost, presence: true

  scope :ordered, -> { order(created_at: :desc) }
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :require_authentication
  # before_action :ensure_can_manage?
  # before_action :validate_organization, only: %i[ index new edit ]
  before_action :set_organization
  before_action :set_service, only: %i[ edit update destroy ]

  def index
    @services = @organization.services.ordered
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params.merge(organization: @organization))

    if @service.save
      redirect_to organization_services_path(@organization.uid)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @service.update(service_params)
      redirect_to organization_services_path(@organization.uid), notice: "Updated successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @service.destroy
    redirect_to organization_services_path(@organization.uid)
  end

  private
    def service_params
      params.require(:service).permit(:name, :description, :cost, :organization_id)
    end

    def validate_organization
      @organization = Organization.find_by(uid: params[:uid])

      head :not_found if @organization.nil?
    end

    def set_organization
      @organization = Organization.find_by(uid: params[:organization_uid])
    end

    def set_service
      @service = Service.find params[:id]
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_service.html.erb
<%= cache service do %>
<tbody class="bg-white divide-y divide-gray-200">
  <tr class="hover:bg-gray-100">
    <td class="p-4 text-sm font-normal text-gray-500 whitespace-nowrap">
      <div class="text-base font-medium text-gray-900 capitalize">
        <%= service.name %>
      </div>
    </td>
    <td class="p-4 text-base font-normal text-gray-900 whitespace-nowrape">
      <%= number_to_currency(service.cost, unit: "₱ ", separator: ".  ", delimiter: "") %>
    </td>
    <td class="max-w-sm p-4 overflow-hidden text-base font-normal text-gray-500 truncate xl:max-w-xs ">
      <%= time_tag service.created_at, "data-local": "time-ago" %>
    </td>
    <td class="p-4 space-x-2 whitespace-nowrap">
    <% if Current.user.can_manage? %>
      <%= link_to edit_organization_service_path(@organization.uid, service), id: "edit_service",
          class: "inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white rounded-lg bg-gigas hover:bg-bluebell focus:ring-4 focus:ring-linkwater" do %>
          <svg class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path><path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"></path></svg>
          Edit
        <% end %>
        <!-- button type="button" id="deleteProductButton" data-drawer-target="drawer-delete-product-default" data-drawer-show="drawer-delete-product-default" aria-controls="drawer-delete-product-default" data-drawer-placement="right" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-apricot rounded-lg hover:bg-red-800 focus:ring-4 focus:ring-red-300">
            <svg class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path></svg>
            Delete
        </!-->
    <% end %>
    </td>
  </tr>
</tbody>
<% end %>

app/views/services/edit.html.erb
<% content_for(:title) { "Organization | Services" } %>

<%= content_for :aside do %>
   <%= render "layouts/shared/sidebar" %>
<% end %>

<%= content_for :header_title do %>
  <ul class="flex items-center text-sm ml-4">
    <li class="text-gray-700 mr-2 font-medium text-md">Services</li>
  </ul>
<% end %>

<%= content_for :header do %>
  <%= render "layouts/shared/navbar" %>
<% end %>

<div class="mx-auto p-6">
  <div class="mb-4 col-span-full xl:mb-2">
    <nav class="flex mb-5" aria-label="Breadcrumb">
      <ol class="inline-flex items-center space-x-1 text-sm font-medium md:space-x-2">
        <li class="inline-flex items-center">
          <%= link_to organization_services_path(Current.organization.uid), class: "inline-flex items-center text-gray-700 hover:text-indigo-600" do %>
          <svg class="w-5 h-5 mr-2.5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"></path>
          </svg>
          Services
          <% end %>
        </li>
        <li>
          <div class="flex items-center">
          <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
          </svg>
          <span class="ml-1 text-gray-400 md:ml-2" aria-current="page">New</span>
          </div>
        </li>
      </ol>
    </nav>
  </div>

<div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:p-6">

  <h3 class="mb-4 text-xl font-medium">Add a service</h3>
  <p class="mt-1 text-sm leading-6 text-gray-600 mb-2">This information will be published in your web page once created.</p>

  <%= form_with model: @service, url: organization_service_path(@organization.uid, @service) do |form| %>

    <%= render "shared/error_messages", object: @service %>

    <div class="grid grid-cols-6 gap-6 mt-4">

      <div class="col-span-6">
        <label for="name" class="block mb-2 text-sm font-medium text-gray-900">Name</label>
        <%= form.text_field :name, id: "name", autocomplete: "name", placeholder: "Name of service", class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" %>
      </div>

      <div class="col-span-6">
        <label for="name" class="block mb-2 text-sm font-medium text-gray-900">Description</label>
        <%= form.text_area :description, id: "description", autocomplete: "description", placeholder: "Description of service", class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" %>
      </div>

      <div class="col-span-6">
        <label for="name" class="block mb-2 text-sm font-medium text-gray-900">Cost</label>
        <%= form.text_field :cost, placeholder: "Cost of service", class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" %>
      </div>

      <div class="col-span-6 md:col-full">
        <button
          class="text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center"
          type="submit"
          id="edit_record"
        >
          Update service
        </button>
        <%= link_to organization_service_path(@organization.uid, @service), data: { turbo_method: :delete } do %>
          <button
            class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center"
            id="delete_record"
          >
            Delete
          </button>
        <% end %>
        <%= link_to "Cancel", organization_services_path(@organization.uid), class: "text-sm font-semibold leading-6 text-gray-700 ml-2" %>
      </div>
    </div>
  <% end %>
</div>

</div>

app/views/services/index.html.erb
<% content_for(:title) { "Organization | Services" } %>

<%= content_for :aside do %>
   <%= render "layouts/shared/sidebar" %>
<% end %>

<%= content_for :header_title do %>
  <ul class="flex items-center text-sm ml-4">
    <li class="text-gray-700 mr-2 font-medium text-md">Services</li>
  </ul>
<% end %>

<%= content_for :header do %>
  <%= render "layouts/shared/navbar" %>
<% end %>

<div class="mx-auto p-6">
  <div class="p-4 bg-white block sm:flex items-center justify-between border-b border-gray-200 lg:mt-1.5">
    <div class="w-full mb-1">
      <div class="mb-4">
          <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl">Services</h1>
      </div>
      <div class="items-center justify-between block sm:flex md:divide-x md:divide-gray-100">
        <div class="flex items-center mb-4 sm:mb-0">
            List of services available in your organization
        </div>

        <%= link_to new_organization_service_url(Current.organization.uid) do %>
          <button id="createProductButton" class="text-white bg-gigas hover:bg-bluebell focus:ring-4 focus:ring-linkwater font-medium rounded-lg text-sm px-5 py-2.5 focus:outline-none " type="button">
              Add new service
          </button>
        <% end if Current.user.can_manage? %>
      </div>
  </div>
</div>

<div class="flex flex-col">
  <div class="overflow-x-auto">
    <div class="inline-block min-w-full align-middle">
      <div class="overflow-hidden shadow">
        <table class="min-w-full divide-y divide-gray-200 table-fixed">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="p-4 text-xs font-medium text-left text-gray-500 uppercase">
                Service name
              </th>
              <th scope="col" class="p-4 text-xs font-medium text-left text-gray-500 uppercase">
                Cost
              </th>
              <th scope="col" class="p-4 text-xs font-medium text-left text-gray-500 uppercase">
                Posted
              </th>
              <th scope="col" class="p-4 text-xs font-medium text-left text-gray-500 uppercase">
                <span class="sr-only">actions</span>
              </th>
            </tr>
          </thead>
          <%= render @services %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/services/new.html.erb
<% content_for(:title) { "Organization | Services" } %>

<%= content_for :aside do %>
   <%= render "layouts/shared/sidebar" %>
<% end %>

<%= content_for :header_title do %>
  <ul class="flex items-center text-sm ml-4">
    <li class="text-gray-700 mr-2 font-medium text-md">Services</li>
  </ul>
<% end %>

<%= content_for :header do %>
  <%= render "layouts/shared/navbar" %>
<% end %>

<div class="mx-auto p-6">
  <div class="mb-4 col-span-full xl:mb-2">
    <nav class="flex mb-5" aria-label="Breadcrumb">
      <ol class="inline-flex items-center space-x-1 text-sm font-medium md:space-x-2">
        <li class="inline-flex items-center">
          <%= link_to organization_services_path(Current.organization.uid), class: "inline-flex items-center text-gray-700 hover:text-indigo-600" do %>
          <svg class="w-5 h-5 mr-2.5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"></path>
          </svg>
          Services
          <% end %>
        </li>
        <li>
          <div class="flex items-center">
          <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
          </svg>
          <span class="ml-1 text-gray-400 md:ml-2" aria-current="page">New</span>
          </div>
        </li>
      </ol>
    </nav>
  </div>

<div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:p-6">

  <h3 class="mb-4 text-xl font-medium">Add a service</h3>
  <p class="mt-1 text-sm leading-6 text-gray-600 mb-2">This information will be published in your web page once created.</p>

  <%= form_with model: @service, url: organization_services_url do |form| %>

    <%= render "shared/error_messages", object: @service %>

    <div class="grid grid-cols-6 gap-6 mt-4">

      <div class="col-span-6">
        <label for="name" class="block mb-2 text-sm font-medium text-gray-900">Name</label>
        <%= form.text_field :name, id: "name", autocomplete: "name", placeholder: "Name of service", class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" %>
      </div>

      <div class="col-span-6">
        <label for="name" class="block mb-2 text-sm font-medium text-gray-900">Description</label>
        <%= form.text_area :description, id: "description", autocomplete: "description", placeholder: "Description of service", class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" %>
      </div>

      <div class="col-span-6">
        <label for="name" class="block mb-2 text-sm font-medium text-gray-900">Cost</label>
        <%= form.text_field :cost, placeholder: "Cost of service", class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" %>
      </div>

      <div class="col-span-6 md:col-full">
        <button
          class="text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center"
          type="submit"
          id="new_record"
        >
          Create service
        </button>
        <%= link_to "Cancel", organization_services_path(Current.organization), class: "text-sm font-semibold leading-6 text-gray-700 ml-2" %>
      </div>
    </div>
  <% end %>
</div>

</div>