config/routes.rb
Rails.application.routes.draw do
  root "organizations#index"

  resource :first_run, only: %i[show create], path: "setup"

  resources :users do
    scope module: "users" do
      resource :profile
    end
  end

  resource :session
  resources :passwords, param: :token

  get "organization/:uid/join/:join_code", to: "users#new", as: :join
  post "organization/:uid/join/:join_code", to: "users#create"

  resources :organizations, param: :uid, except: %i[ index show ] do
    scope module: "organizations" do
      resource :join_code, only: :create
    end
    resources :patient_records
    resources :services
  end

  get "/:slug", to: "organizations#show", as: :slugged_organization

  get "organization/:uid/administratorships", to: "administratorships#index",  constraints: { uid: /\d+/ }, as: :slugged_organization_administratorships
  get "organization/:uid/administratorships/:id", to: "administratorships#index",  constraints: { uid: /\d+/ }, as: :slugged_organization_administratorship
  patch "organization/:uid/administratorships/:id", to: "administratorships#update", constraints: { uid: /\d+/ }

  get "up", to: "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker", to: "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest", to: "rails/pwa#manifest", as: :pwa_manifest
end

app/views/layouts/shared/_navbar.html.erb
<div class="py-2 px-6 bg-white flex items-center shadow-md shadow-black/5 sticky top-0 left-0 z-30">

  <button type="button" class="text-lg text-gray-600 sidebar-toggle" data-action="click->sidebar#toggle">
    <%= image_tag "hamburger.svg", class: "w-4 h-4 text-gray-800 dark:text-white" %>
  </button>

  <%= yield :header_title %>

  <ul class="ml-auto flex items-center">
    <li class="mr-1 dropdown">
      <button type="button" class="dropdown-toggle text-gray-400 w-8 h-8 rounded flex items-center justify-center hover:bg-gray-50 hover:text-gray-600">
        <i class="ri-search-line"></i>
      </button>
      <div
        class="dropdown-menu shadow-md shadow-black/5 z-30 hidden max-w-xs w-full bg-white rounded-md border border-gray-100"
        data-popper-id="popper-0"
        data-popper-placement="bottom-end"
        style="position: absolute; inset: 0px 0px auto auto; margin: 0px; transform: translate3d(-104px, 48px, 0px);"
      >
        <form action="" class="p-4 border-b border-b-gray-100">
          <div class="relative w-full">
            <input type="text" class="py-2 pr-4 pl-10 bg-gray-50 w-full outline-none border border-gray-100 rounded-md text-sm focus:border-blue-500" placeholder="Search..." />
            <i class="ri-search-line absolute top-1/2 left-4 -translate-y-1/2 text-gray-400"></i>
          </div>
        </form>
        <div class="mt-3 mb-2">
          <div class="text-[13px] font-medium text-gray-400 ml-4 mb-2">Recently</div>
          <ul class="max-h-64 overflow-y-auto">
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">Create landing page</div>
                  <div class="text-[11px] text-gray-400">$345</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">Create landing page</div>
                  <div class="text-[11px] text-gray-400">$345</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">Create landing page</div>
                  <div class="text-[11px] text-gray-400">$345</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">Create landing page</div>
                  <div class="text-[11px] text-gray-400">$345</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">Create landing page</div>
                  <div class="text-[11px] text-gray-400">$345</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">Create landing page</div>
                  <div class="text-[11px] text-gray-400">$345</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">Create landing page</div>
                  <div class="text-[11px] text-gray-400">$345</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">Create landing page</div>
                  <div class="text-[11px] text-gray-400">$345</div>
                </div>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li class="dropdown">
      <button type="button" class="dropdown-toggle text-gray-400 w-8 h-8 rounded flex items-center justify-center hover:bg-gray-50 hover:text-gray-600">
        <i class="ri-notification-3-line"></i>
      </button>
      <div
        class="dropdown-menu shadow-md shadow-black/5 z-30 hidden max-w-xs w-full bg-white rounded-md border border-gray-100"
        data-popper-id="popper-1"
        data-popper-placement="bottom-end"
        style="position: absolute; inset: 0px 0px auto auto; margin: 0px; transform: translate3d(-68px, 48px, 0px);"
      >
        <div class="flex items-center px-4 pt-4 border-b border-b-gray-100 notification-tab">
          <button type="button" data-tab="notification" data-tab-page="notifications" class="text-gray-400 font-medium text-[13px] hover:text-gray-600 border-b-2 border-b-transparent mr-4 pb-1 active">Notifications</button>
          <button type="button" data-tab="notification" data-tab-page="messages" class="text-gray-400 font-medium text-[13px] hover:text-gray-600 border-b-2 border-b-transparent mr-4 pb-1">Messages</button>
        </div>
        <div class="my-2">
          <ul class="max-h-64 overflow-y-auto" data-tab-for="notification" data-page="notifications">
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">New order</div>
                  <div class="text-[11px] text-gray-400">from a user</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">New order</div>
                  <div class="text-[11px] text-gray-400">from a user</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">New order</div>
                  <div class="text-[11px] text-gray-400">from a user</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">New order</div>
                  <div class="text-[11px] text-gray-400">from a user</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">New order</div>
                  <div class="text-[11px] text-gray-400">from a user</div>
                </div>
              </a>
            </li>
          </ul>
          <ul class="max-h-64 overflow-y-auto hidden" data-tab-for="notification" data-page="messages">
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">John Doe</div>
                  <div class="text-[11px] text-gray-400">Hello there!</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">John Doe</div>
                  <div class="text-[11px] text-gray-400">Hello there!</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">John Doe</div>
                  <div class="text-[11px] text-gray-400">Hello there!</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">John Doe</div>
                  <div class="text-[11px] text-gray-400">Hello there!</div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="py-2 px-4 flex items-center hover:bg-gray-50 group">
                <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
                <div class="ml-2">
                  <div class="text-[13px] text-gray-600 font-medium truncate group-hover:text-blue-500">John Doe</div>
                  <div class="text-[11px] text-gray-400">Hello there!</div>
                </div>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li class="dropdown ml-3">
      <button type="button" class="dropdown-toggle flex items-center">
        <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded block object-cover align-middle" />
      </button>
      <ul
        class="dropdown-menu shadow-md shadow-black/5 z-30 hidden py-1.5 rounded-md bg-white border border-gray-100 w-full max-w-[140px]"
        data-popper-id="popper-2"
        data-popper-placement="bottom-end"
        style="position: absolute; inset: 0px 0px auto auto; margin: 0px; transform: translate3d(-24px, 48px, 0px);"
      >
        <li>
          <a href="#" class="flex items-center text-[13px] py-1.5 px-4 text-gray-600 hover:text-blue-500 hover:bg-gray-50">Profile</a>
        </li>
        <li>
          <a href="#" class="flex items-center text-[13px] py-1.5 px-4 text-gray-600 hover:text-blue-500 hover:bg-gray-50">Settings</a>
        </li>
        <li>
          <a href="#" class="flex items-center text-[13px] py-1.5 px-4 text-gray-600 hover:text-blue-500 hover:bg-gray-50">Logout</a>
        </li>
      </ul>
    </li>
  </ul>
</div>

app/views/layouts/shared/_sidebar.html.erb
<div data-sidebar-target="menu" data-sidebar-target="menu" class="fixed left-0 top-0 w-64 h-full bg-gigas text-primary p-4 z-50 transition-transform">
  <%= link_to root_path, class:"flex items-center pb-4 border-b border-b-primary" do %>
    <img src="https://placehold.co/32x32" alt="" class="w-8 h-8 rounded object-cover" />
    <span class="text-lg font-medium text-white ml-3">
      <%= Current.organization&.name.truncate(20) %>
    </span>
  <% end %>
  <ul class="mt-4 text-lg">
    <li class="mb-2 group active">
      <%= link_to root_path, class:"flex items-center py-2 px-4 text-gray-300 hover:bg-bluebell hover:text-gray-100 rounded-md" do %>
        <svg class="w-6 h-6 mr-3 text-lg" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path>
          <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path>
        </svg>
        <span class="text-sm">Dashboard</span>
      <% end %>
    </li>
    <li class="mb-2 group">
      <%= link_to organization_patient_records_path(Current.organization.uid), class:"flex items-center py-2 px-4 text-gray-300 hover:bg-bluebell hover:text-gray-100 rounded-md" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-3 text-lg">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 0 1 4.5 9.75h15A2.25 2.25 0 0 1 21.75 12v.75m-8.69-6.44-2.12-2.12a1.5 1.5 0 0 0-1.061-.44H4.5A2.25 2.25 0 0 0 2.25 6v12a2.25 2.25 0 0 0 2.25 2.25h15A2.25 2.25 0 0 0 21.75 18V9a2.25 2.25 0 0 0-2.25-2.25h-5.379a1.5 1.5 0 0 1-1.06-.44Z" />
        </svg>
        <span class="text-sm">Patient Records</span>
      <% end %>
    </li>
    <li class="mb-2 group">
      <%= link_to organization_services_path(Current.organization.uid), class:"flex items-center py-2 px-4 text-gray-300 hover:bg-bluebell hover:text-gray-100 rounded-md" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-3 text-lg">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 0 1 4.5 9.75h15A2.25 2.25 0 0 1 21.75 12v.75m-8.69-6.44-2.12-2.12a1.5 1.5 0 0 0-1.061-.44H4.5A2.25 2.25 0 0 0 2.25 6v12a2.25 2.25 0 0 0 2.25 2.25h15A2.25 2.25 0 0 0 21.75 18V9a2.25 2.25 0 0 0-2.25-2.25h-5.379a1.5 1.5 0 0 1-1.06-.44Z" />
        </svg>
        <span class="text-sm">Services</span>
      <% end %>
    </li>
    <li class="mb-2 group">
      <%= link_to "", class:"flex items-center py-2 px-4 text-gray-300 hover:bg-bluebell hover:text-gray-100 rounded-md cursor-not-allowed" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-3 text-lg">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5" />
        </svg>
        <span class="text-sm">Appointment</span>
      <% end %>
    </li>
    <li class="mb-2 group">
      <%= link_to users_path, class:"flex items-center py-2 px-4 text-gray-300 hover:bg-bluebell hover:text-gray-100 rounded-md" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-3 text-lg">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 0 0 2.625.372 9.337 9.337 0 0 0 4.121-.952 4.125 4.125 0 0 0-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 0 1 8.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0 1 11.964-3.07M12 6.375a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0Zm8.25 2.25a2.625 2.625 0 1 1-5.25 0 2.625 2.625 0 0 1 5.25 0Z" />
        </svg>

        <span class="text-sm">Users</span>
      <% end %>
    </li>
  </ul>
</div>
<div class="fixed top-0 left-0 w-full h-full bg-black/50 z-40 md:hidden sidebar-overlay" data-sidebar-target="overlay" data-action="click->sidebar#closeSidebar"></div>