config/routes.rb
Rails.application.routes.draw do
  root "organizations#index"

  resource :first_run, only: %i[show create], path: "setup"

  resources :users do
    scope module: "users" do
      resource :profile
    end
  end

  resource :session
  resources :passwords, param: :token

  get "organization/:uid/join/:join_code", to: "users#new", as: :join
  post "organization/:uid/join/:join_code", to: "users#create"

  resources :organizations, param: :uid, except: %i[ index show ] do
    scope module: "organizations" do
      resource :join_code, only: :create
    end
    resources :patient_records
    resources :services
  end

  get "/:slug", to: "organizations#show", as: :slugged_organization

  get "organization/:uid/administratorships", to: "administratorships#index",  constraints: { uid: /\d+/ }, as: :slugged_organization_administratorships
  get "organization/:uid/administratorships/:id", to: "administratorships#index",  constraints: { uid: /\d+/ }, as: :slugged_organization_administratorship
  patch "organization/:uid/administratorships/:id", to: "administratorships#update", constraints: { uid: /\d+/ }

  get "up", to: "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker", to: "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest", to: "rails/pwa#manifest", as: :pwa_manifest
end

app/models/administratorship.rb
class Administratorship < ApplicationRecord
  include Role

  belongs_to :user
  belongs_to :organization

  validates :user_id, uniqueness: { message: "is already an administrator of an organization." }

  scope :ordered, -> {
    order(
      Arel.sql("CASE WHEN role = 'owner' THEN 1 WHEN role = 'staff' THEN 2 WHEN role = 'patient' THEN 3 ELSE 4 END"),
      created_at: :desc
    )
  }
end

app/models/administratorship/role.rb
module Administratorship::Role
  extend ActiveSupport::Concern

  included do
    enum :role, %i[ patient staff owner ], default: :patient
  end

  def can_manage?
    owner? || staff?
  end
end

app/controllers/administratorships_controller.rb
class AdministratorshipsController < ApplicationController
  before_action :require_authentication

  before_action :set_organization
  before_action :set_administratorships, only: :index
  before_action :set_administratorship, only: %i[ edit update ]

  def index
  end

  def edit
  end

  def update
    @administratorship.update(role_params)
    redirect_to users_path
  end

  private
    def role_params
      { role: params.require(:administratorship)[:role].presence_in(%w[patient staff owner]) || "patient" }
    end

    def set_organization
      @organization = Current.organization
    end

    def set_administratorships
      @administatorhips = @organization.administratorships
    end

    def set_administratorship
      @administratorship = Administratorship.find params[:id]
    end
end

app/views/administratorships/_administratorship.html.erb
<li class="py-4">
  <div class="flex justify-between xl:block 2xl:flex align-center 2xl:space-x-4">
    <div class="flex space-x-4 xl:mb-4 2xl:mb-0">
      <div>
        <img class="w-6 h-6 rounded-full" src="https://flowbite-admin-dashboard.vercel.app/images/users/bonnie-green.png" alt="Bonnie image" />
      </div>
      <div class="flex-1 min-w-0">
        <p class="text-base font-semibold text-gray-900 leading-none truncate mb-0.5">
          <%= administratorship.user.name %>
        </p>
        <p class="mb-1 text-sm font-normal truncate text-indigo-700">
          <%= administratorship.user&.administratorship.role.capitalize %>
        </p>
        <p class="text-xs font-medium text-gray-500">
          <%= administratorship.user.email_address %>
        </p>
      </div>
    </div>
    <div class="inline-flex items-center w-auto xl:w-full 2xl:w-auto">
      <%= form_with model: administratorship, url: slugged_organization_administratorship_path(@organization.uid, administratorship.id), data: { controller: "administrator", action: "change->administrator#submitOnChange" }, method: :patch do |form| %>
        <%= form.select :role,
                        options_for_select(Administratorship.roles.keys.map { |role| [role.humanize, role] }, administratorship.role),
                        { },
                        class: "bg-gray-50 border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5 mr-4",
                        disabled: administratorship.user.current? && Current.user.can_manage? %>
      <% end %>
    </div>
  </div>
</li>

app/views/administratorships/index.html.erb
<% content_for(:title) { "Organization | #{@organization.name}" } %>

<%= content_for :aside do %>
   <%= render "layouts/shared/sidebar" %>
<% end %>

<%= content_for :header_title do %>
  <ul class="flex items-center text-sm ml-4">
    <li class="mr-2">
      <a class="text-gray-600 font-medium text-md">Dashboard</a>
    </li>
  </ul>
<% end %>

<%= content_for :header do %>
  <%= render "layouts/shared/navbar" %>
<% end %>

<div class="grid grid-cols-1 px-4 pt-6 xl:grid-cols-3 xl:gap-4">

  <div class="mb-4 col-span-full xl:mb-2">
    <nav class="flex mb-5" aria-label="Breadcrumb">
      <ol class="inline-flex items-center space-x-1 text-sm font-medium md:space-x-2">
        <li class="inline-flex items-center">
          <a href="#" class="inline-flex items-center text-gray-700 hover:text-indigo-600">
          <svg class="w-5 h-5 mr-2.5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"></path>
          </svg>
          Home
          </a>
        </li>
        <li>
          <div class="flex items-center">
          <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
          </svg>
          <a href="#" class="ml-1 text-gray-700 hover:text-indigo-600 md:ml-2 ">Users</a>
          </div>
        </li>
        <li>
          <div class="flex items-center">
          <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
          </svg>
          <span class="ml-1 text-gray-400 md:ml-2" aria-current="page">Settings</span>
          </div>
        </li>
      </ol>
    </nav>
    <h1 class="text-xl font-medium text-gray-800 sm:text-2xl">User settings</h1>
  </div>

  <!-- grid boxes -->
<div class="col-span-full xl:col-auto">
  <div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm 2xl:col-span-2 sm:p-6">
    <div class="items-center sm:flex xl:block 2xl:flex sm:space-x-4 xl:space-x-0 2xl:space-x-4">
      <img class="mb-4 rounded-lg w-28 h-28 sm:mb-0 xl:mb-4 2xl:mb-0" src="https://flowbite-admin-dashboard.vercel.app/images/users/bonnie-green-2x.png" alt="Jese picture" />
      <div>
        <h3 class="mb-1 text-xl font-bold text-gray-900">Profile picture</h3>
        <div class="mb-4 text-sm text-gray-500">
          JPG, GIF or PNG. Max size of 800K
        </div>
        <div class="flex items-center space-x-4">
          <button
            type="button"
            class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white rounded-lg bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300"
          >
            <svg class="w-4 h-4 mr-2 -ml-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M5.5 13a3.5 3.5 0 01-.369-6.98 4 4 0 117.753-1.977A4.5 4.5 0 1113.5 13H11V9.413l1.293 1.293a1 1 0 001.414-1.414l-3-3a1 1 0 00-1.414 0l-3 3a1 1 0 001.414 1.414L9 9.414V13H5.5z"></path>
              <path d="M9 13h2v5a1 1 0 11-2 0v-5z"></path>
            </svg>
            Upload picture
          </button>
          <button
            type="button"
            class="py-2 px-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-indigo-700 focus:z-10 focus:ring-4 focus:ring-gray-200"
          >
            Delete
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm 2xl:col-span-2 sm:p-6">
    <h3 class="mb-4 text-xl font-semibold">User information</h3>
    <form action="#">
      <div class="grid grid-cols-6 gap-6">
        <div class="col-span-6">
          <label for="first-name" class="block mb-2 text-sm font-medium text-gray-900">First Name</label>
          <input
            type="text"
            name="first-name"
            id="first-name"
            class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5"
            placeholder="Bonnie"
            required=""
          />
        </div>

        <div class="col-span-6">
          <label for="first-name" class="block mb-2 text-sm font-medium text-gray-900">First Name</label>
          <input
            type="text"
            name="first-name"
            id="first-name"
            class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5"
            placeholder="Bonnie"
            required=""
          />
        </div>

        <div class="col-span-6 sm:col-full">
          <button
            class="text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center"
            type="submit"
          >
            Save all
          </button>
        </div>
      </div>
    </form>
  </div>
  </div>

  <div class="col-span-2">

    <div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm 2xl:col-span-2">
    <h3 class="mb-4 text-xl font-semibold">Share to invite your patient in your organization</h3>

    <div class="mb-4">
      <% url = join_url(Current.organization.uid, Current.organization.join_code) %>

      <% if Current.user.can_manage? %>
      <div>
      <strong>Share invite to more people</strong>
      <span>
      <input type="text" id="invite_url" value="<%= url %>" readonly>
      </span>
      </div>

      <%= button_to organization_join_code_path(Current.organization.uid) do %>
      <span class="for-screen-reader">Regenerate join link</span>
      <% end %>
      <% end %>
    </div>

    <div class="mb-4">
      <label for="settings-language" class="block mb-2 text-sm font-medium text-gray-900">Strictly share the link to patient only, and advise to regenerate the code after the patient registered.</label>
      <select
        id="settings-language"
        name="countries"
        class="bg-gray-50 border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5"
      >
        <option>English (US)</option>
        <option>Italiano</option>
        <option>Français (France)</option>
        <option>正體字</option>
        <option>Español (España)</option>
        <option>Deutsch</option>
        <option>Português (Brasil)</option>
      </select>
    </div>
    <div class="mb-6">
      <label for="settings-timezone" class="block mb-2 text-sm font-medium text-gray-900">Time Zone</label>
      <select
        id="settings-timezone"
        name="countries"
        class="bg-gray-50 border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5"
      >
        <option>GMT+0 Greenwich Mean Time (GMT)</option>
        <option>GMT+1 Central European Time (CET)</option>
        <option>GMT+2 Eastern European Time (EET)</option>
        <option>GMT+3 Moscow Time (MSK)</option>
        <option>GMT+5 Pakistan Standard Time (PKT)</option>
        <option>GMT+8 China Standard Time (CST)</option>
        <option>GMT+10 Eastern Australia Standard Time (AEST)</option>
      </select>
    </div>
    <div>
      <button class="text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
        Regenarate join link
      </button>
    </div>
  </div>

  <div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm 2xl:col-span-2 sm:p-6">
    <div class="flow-root">
      <h3 class="text-xl font-semibold">Other accounts</h3>
      <ul class="mb-6 divide-y divide-gray-200">
        <%= render @administatorhips %>
      </ul>
    </div>
  </div>
</div>

</div>