config/routes.rb
Rails.application.routes.draw do
  root "organizations#index"

  resource :first_run, only: %i[show create], path: "setup"

  resources :users do
    scope module: "users" do
      resource :profile
    end
  end

  resource :session
  resources :passwords, param: :token

  get "organization/:uid/join/:join_code", to: "users#new", as: :join
  post "organization/:uid/join/:join_code", to: "users#create"

  resources :organizations, param: :uid, except: %i[ index show ] do
    scope module: "organizations" do
      resource :join_code, only: :create
    end
    resources :patient_records
    resources :services
  end

  get "/:slug", to: "organizations#show", as: :slugged_organization

  get "organization/:uid/administratorships", to: "administratorships#index",  constraints: { uid: /\d+/ }, as: :slugged_organization_administratorships
  get "organization/:uid/administratorships/:id", to: "administratorships#index",  constraints: { uid: /\d+/ }, as: :slugged_organization_administratorship
  patch "organization/:uid/administratorships/:id", to: "administratorships#update", constraints: { uid: /\d+/ }

  get "up", to: "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker", to: "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest", to: "rails/pwa#manifest", as: :pwa_manifest
end

app/models/organization.rb
class Organization < ApplicationRecord
  include Sluggable, Joinable, Findable

  belongs_to :user
  has_many :patient_records, dependent: :destroy
  has_many :administratorships, dependent: :destroy
  has_many :users, through: :administratorships
  has_many :services, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  after_create :assign_administrator

  private
    def assign_administrator
      Administratorship.create!(user: user, organization: self, role: :owner)
    end
end

app/models/organization/findable.rb
module Organization::Findable
  extend ActiveSupport::Concern

  included do
    before_create { self.uid = generate_uid }
  end

  private
    def generate_uid
      self.uid = loop do
        randomizer = SecureRandom.hex(4).to_i(16) & 10000000
        break randomizer unless self.class.exists?(uid: randomizer)
      end
    end
end

app/models/organization/joinable.rb
module Organization::Joinable
  extend ActiveSupport::Concern

  included do
    before_create { self.join_code = generate_join_code }
  end

  def reset_join_code
    update! join_code: generate_join_code
  end

  private
    def generate_join_code
      SecureRandom.alphanumeric(12).scan(/.{4}/).join("-")
    end
end

app/models/organization/sluggable.rb
module Organization::Sluggable
  extend ActiveSupport::Concern

  included do
    before_save :generate_slug, if: -> { slug.blank? }
  end

  def generate_slug
    self.slug = name.parameterize || slug.parameterize
  end
end

app/controllers/organizations/join_codes_controller.rb
class Organizations::JoinCodesController < ApplicationController
  before_action :ensure_can_manage?

  def create
    Current.organization.reset_join_code
    redirect_to users_path
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  allow_unauthenticated_access only: :show

  before_action :current_organization, only: :index
  before_action :check_if_patient, only: :index
  before_action :check_if_no_organization, only: :new
  before_action :find_organization, only: :show
  before_action :set_organization, only: %i[ edit update destroy ]
  before_action :ensure_can_manage?, only: %i[ edit update destroy ]
  before_action :resume_session

  def index
  end

  def new
    @organization = Organization.new
  end

  def create
    Organization.create!(organization_params.merge(user: Current.user))

    redirect_to root_url
  end

  def show
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def edit
  end

  def update
    if @organization.update! organization_params
      redirect_to root_url, notice: "Successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @organization.destroy
    redirect_to root_url
  end

  private
    def check_if_no_organization
      redirect_to root_url if Current.organization.present?
    end

    def find_organization
      @organization = Organization.find_by(slug: params[:slug])

      head :not_found if @organization.nil?
    end

    def set_organization
      @organization = Organization.find_by(uid: params[:uid])
    end

    def organization_params
      params.require(:organization).permit(:name, :slug, :uid, :join_code)
    end

    def current_organization
      @organization = Current.organization

      redirect_to new_organization_url if @organization.nil?
    end

    def check_if_patient
      redirect_to slugged_organization_path(Current.organization.uid, Current.organization.slug) if Current.user&.administratorship.patient?
  end
end

app/views/organizations/edit.html.erb
<% content_for(:title) { "Organization | #{@organization.name}" } %>

<%= content_for :aside do %>
   <%= render "layouts/shared/sidebar" %>
<% end %>

<%= content_for :header_title do %>
  <ul class="flex items-center text-sm ml-4">
    <li class="mr-2">
      <%= link_to "Organization", root_path, class: "text-gray-600 font-medium text-md" %>
    </li>
    <li class="text-gray-700 mr-2 font-medium text-md">/</li>
    <li class="text-gray-700 mr-2 font-medium text-md">
      <%= @organization.uid %>
    </li>
    <li class="text-gray-700 mr-2 font-medium text-md">/</li>
    <li class="text-gray-500 mr-2 font-medium text-md">Edit</li>
  </ul>
<% end %>

<%= content_for :header do %>
  <%= render "layouts/shared/navbar" %>
<% end %>

<div class="mx-auto p-6">

<div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:p-6">
  <h3 class="mb-4 text-xl font-medium">Edit organization</h3>
  <p class="mt-1 text-sm leading-6 text-gray-600">This information will be displayed publicly so be careful what you share.</p>

  <%= form_with model: @organization, url: organization_path(@organization.uid) do |form| %>
    <div class="grid grid-cols-6 gap-6 mt-4">

      <div class="col-span-6">
        <label for="name" class="block mb-2 text-sm font-medium text-gray-900">Name</label>
        <%= form.text_field :name, id: "name", autocomplete: "name", class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" %>
      </div>

      <div class="col-span-6">
        <%= form.label :slug, 'URL', class: "block mb-2 text-sm font-medium text-gray-900" %>
        <div class="mt-2">
          <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
            <span class="flex select-none items-center pl-3 text-gray-500 sm:text-sm"><%= root_url %></span>
            <%= form.text_field :slug, placeholder: "janesmith", class: "block flex-1 border-0 bg-transparent py-2.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
          </div>
        </div>
      </div>

      <div class="col-span-6 sm:col-span-3">
        <label for="name" class="block mb-2 text-sm font-medium text-gray-900">Organization ID</label>
        <%= form.text_field :uid, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5", readonly: true %>
      </div>

      <div class="col-span-6 sm:col-span-3">
        <label for="name" class="block mb-2 text-sm font-medium text-gray-900">Join Code</label>
        <%= form.text_field :join_code, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5", readonly: true %>
      </div>

      <div class="col-span-6 sm:col-full">
        <button
          class="text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center"
          type="submit"
          id="edit_organization"
        >
          Update
        </button>
        <%= link_to "Cancel", root_path, class: "text-sm font-semibold leading-6 text-gray-700 ml-2" %>
      </div>
    </div>
  <% end %>
</div>

</div>

app/views/organizations/index.html.erb
<% content_for(:title) { "Organization | #{@organization.name}" } %>

<%= content_for :aside do %>
   <%= render "layouts/shared/sidebar" %>
<% end %>

<%= content_for :header_title do %>
  <ul class="flex items-center text-sm ml-4">
    <li class="mr-2">
      <a class="text-gray-600 font-medium text-md">Dashboard</a>
    </li>
  </ul>
<% end %>

<%= content_for :header do %>
  <%= render "layouts/shared/navbar" %>
<% end %>

<div class="mx-auto p-6">

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
    <div class="bg-white rounded-md border border-gray-100 p-6 shadow-md shadow-black/5">
      <div class="flex justify-between mb-6">
        <div>
          <div class="text-2xl font-semibold mb-1"><%= Current.organization.patient_records.count %></div>
          <div class="text-sm font-medium text-gray-400">Patient Records</div>
        </div>
      </div>
      <%= link_to "View records", organization_patient_records_path(Current.organization.uid), class: "text-apricot font-medium text-sm" %>
    </div>

    <div class="bg-white rounded-md border border-gray-100 p-6 shadow-md shadow-black/5">
      <div class="flex justify-between mb-6">
        <div>
          <div class="text-2xl font-semibold mb-1"><%= Current.organization.users.count %></div>
          <div class="text-sm font-medium text-gray-400">Total Patients</div>
        </div>
      </div>
      <%= link_to "View patients", organization_patient_records_path(Current.organization.uid), class: "text-bluebell font-medium text-sm" %>
    </div>
  </div>

</div>

<div class="mx-auto p-12">
  <%= link_to "Show page", slugged_organization_url(Current.organization.slug) unless Current.user.organization.nil? %>

  <% if Current.user.can_manage? %>
    <%= link_to "Edit organization", edit_organization_url(@organization.uid) %>
  <% end %>
</div>

app/views/organizations/new.html.erb
<% content_for(:title) { "Setup organzization" } %>

<div class="mx-auto p-6">

  <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">

  <div class="space-y-12">
    <div class="bg-white border border-gray-100 shadow-md shadow-black/5 p-6 rounded-md border-b border-gray-900/10">
      <h2 class="text-base font-semibold leading-7 text-gray-900">Organization</h2>
      <p class="mt-1 text-sm leading-6 text-gray-600">This information will be displayed publicly so be careful what you share.</p>

      <%= form_with model: @organization, class: "" do |form| %>
        <div class="sm:col-span-4 pb-6">
          <label for="name" class="block text-sm font-medium leading-6 text-gray-900">Name</label>
          <div class="mt-2">
            <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
              <%= form.text_field :name, id: "name", autocomplete: "name", class: "block flex-1 border-0 bg-transparent py-1.5 pl-3 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
            </div>
          </div>
        </div>

        <div>
          <button type="submit" id="edit_organization" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Save</button>
        </div>
      <% end %>

    </div>
  </div>

  </div>

</div>